package ru.objectsfill.types.array;

import ru.objectsfill.object_param.Fill;
import ru.objectsfill.service.ElementCreationService;

import java.lang.reflect.Array;
import java.lang.reflect.Field;

import static ru.objectsfill.types.primitive_type.PrimitiveTypeName.getByName;
import static ru.objectsfill.utils.FieldUtils.getObjectUnaryOperator;

/**
 * Creates and fills arrays (both reference and primitive types) with randomly generated values.
 */
public class FillArray {

    /**
     * Creates an array of the specified type and fills it with generated values.
     *
     * @param fieldType the array or component type
     * @param fill      the generation parameters
     * @param <T>       the component type
     * @return the filled array
     */

    public <T> Object[] createArray(Class<T> fieldType, Fill fill) {
        return createArray(fieldType, fill, null);
    }

    /**
     * Creates an array of the specified type and fills it with generated values.
     * Dispatches to specialized handling for primitive arrays or reference arrays.
     *
     * @param fieldType the array or component type
     * @param fill      the generation parameters
     * @param field     the field for which the array is generated (may be {@code null})
     * @param <T>       the component type
     * @return the filled array
     */

    public <T> Object[] createArray(Class<T> fieldType, Fill fill, Field field) {

        Class<?> componentType = fieldType.getComponentType() == null ? fieldType : fieldType.getComponentType();

        if(getByName(componentType.getName()) != null) {
            return forPrimitiveArrays(fill, componentType, field);
        } else {
            return forReferenceArrays(fill, componentType, field);
        }
    }

    /**
     * Creates a typed array for reference (non-primitive) component types and fills each element
     * with a value generated by {@link ElementCreationService}.
     *
     * @param fill          the generation parameters
     * @param componentType the component type of the array
     * @param field         the source field (may be {@code null})
     * @param <T>           the component type
     * @return the filled array
     */
    @SuppressWarnings("unchecked")
    private <T> T[] forReferenceArrays(Fill fill, Class<?> componentType, Field field) {
        T[] genericArray = (T[]) Array.newInstance(componentType, fill.getCollectionSize());
        for (int i = 0; i < genericArray.length; i++) {
            Object t = getObjectUnaryOperator(fill, field).apply(new ElementCreationService().generateSingleValue(componentType, fill));
            genericArray[i] = (T) t;
        }
        return genericArray;
    }

    /**
     * Creates an {@code Object[]} for primitive-compatible component types and fills each element
     * with a value generated by {@link ElementCreationService}.
     *
     * @param fill          the generation parameters
     * @param componentType the primitive component type
     * @param field         the source field (may be {@code null})
     * @return the filled array
     */
    private static Object[] forPrimitiveArrays(Fill fill, Class<?> componentType, Field field) {
        Object[] genericArray = new Object[fill.getCollectionSize()];
        for (int i = 0; i < genericArray.length; i++) {
            Object t = getObjectUnaryOperator(fill, field).apply(new ElementCreationService().generateSingleValue(componentType, fill));
            genericArray[i] = t;
        }
        return genericArray;
    }

}
